[package]
name = "text_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"

[dependencies.crossterm]
version = "0.12"
default-features = false
features = ["cursor", "screen"]
